### ISSUE TITLE
UnsafeMutablePointer.deinitialize with negative count

### ISSUE THREAD

**Issue by konsdor** [chihayafuru/SampleOfEV3IOS#1]
Hi @chihayafuru,
Thank you for your great work!
I am trying to use your sample in my robotics project.
When I use values from the sensor to control the EV3 like here:
       let timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { timer in print(self.xTrack, self.yTrack)    
        if Double(self.xTrack ?? 0.5) < 0.5 && Double(self.yTrack ?? 0.5) < 0.5 {
                print("right_forward")            
                self.brick!.directCommand.turnMotorAtSpeed(onPorts: [.B], withSpeed: 10)
                self.brick!.directCommand.turnMotorAtSpeed(onPorts: [.A], withSpeed: 0)

it crashes after some time with Fatal error: "UnsafeMutablePointer.deinitialize with negative count"
It happens at "let mData = writeBuffer.remove(at: 0)" in com.ev3ios.connection.queue
It gets better after I increased BufferSize and SleepTime, but still crashing after few seconds.
How can I fix it? 

Thanks,
Konstantin

**Comment by chihayafuru** [comment]
It is thought to be caused by multiple threads modifying the array "writeBuffer" at the same time.
I will fix these bugs. Please wait a moment.

**Comment by chihayafuru** [comment]
I fixed the code.

**Comment by konsdor** [comment]
Thanks a lot!

**Comment by konsdor** [comment]
Hi @chihayafuru,

Thank you for solving the issue with UnsafeMutablePointer.
But now when I send variables from sensors (errX and errY) to EV3
let c = Ev3Command(commandType: .directNoReply)
c.stepMotorSync(ports: [.A, .B], speed: Int16(self.errY ?? 0), turnRatio: Int16(self.errX ?? 0), step: 1000000, brake: false )
c.startMotor(ports: [.A, .B])
self.brick?.sendCommand(c)

I am getting Fatal error: "Index out of range" here:
    private func dismissCommandsIfNeeded(){
        if(writeBuffer.count > maxBufferSize){
            for _ in 1...maxBufferSize {
                self.queue.async {
                    self.writeBuffer.remove(at: 1)
                }
            
in the E3Connection.swift.

Could you please look into this?

Thanks,
Konstantin

**Comment by chihayafuru** [comment]
I fixed the bug "Index out of range".
I think that your app code are calling the EV3 APIs again and again in short time.
You had better insert the wait time in your loop code.

**Comment by konsdor** [comment]
Cool! You are genius!!! The issue has gone.

**Comment by konsdor** [comment]
Hi @chihayafuru,

I am trying to control ev3 though WiFi. I was able to connect, but can't send direct commands. Do you have any idea how to change ev3connection in order to use socket instead of EAAccessory?

Thanks,
Konstantin
